package com.cpayment.custody.domain.event;

import java.time.Instant;
import java.util.UUID;

/**
 * Envelope around a CustodyEvent. eventId is generated by the adapter and used by
 * cpayment downstream to dedupe re-deliveries. providerEventId is the upstream id
 * for tracing. Raw provider payloads stay inside the adapter and are NOT exposed
 * here — domain logic must not branch on provider specifics.
 */
public record CustodyEventEnvelope(
    UUID eventId,
    Instant occurredAt,
    Instant receivedAt,
    String providerName,
    String providerEventId,
    CustodyEvent event
) {}
